In [1]:
import pandas as pd
import os

In [5]:
a = pd.read_csv("../data/happiness_project/world_happiness_2017.csv", sep=';', decimal=',')

a

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,3,Iceland,Western Europe,7.504,7.91458,1.00000,71,0.95277,0.56742,0.33066
1,15,Ireland,Western Europe,6.977,8.20897,0.96750,71,0.87066,0.51053,0.64265
2,2,Denmark,Western Europe,7.522,7.92394,0.96309,70,0.95102,0.42392,0.86316
3,47,Uzbekistan,Commonwealth of Independent States,5.971,4.20385,0.96175,62,1.00000,0.49636,0.53096
4,8,New Zealand,North America and ANZ,7.314,7.51407,0.96127,71,0.93287,0.59661,0.82449
...,...,...,...,...,...,...,...,...,...,...
150,136,Malawi,Sub-Saharan Africa,3.970,1.24784,0.31825,56,0.70933,0.34265,0.15660
151,143,Benin,Sub-Saharan Africa,3.657,2.30433,0.27028,53,0.64712,0.24813,0.13123
152,150,Togo,Sub-Saharan Africa,3.495,1.63273,0.26815,54,0.57794,0.23494,0.20604
153,152,Syria,Middle East and North Africa,3.462,4.15420,0.24594,62,0.12387,0.58904,0.32596
154,155,Central African Republic,Sub-Saharan Africa,2.693,0.00000,0.00000,48,0.41146,0.33514,0.12183

In [3]:
s = '../data/happiness_project/world_happiness_2015.csv'
s.split("_")[-1].split(".")[0]

'2015'

In [12]:
directory = '../data/happiness_project/'
all_data = []

for file in os.listdir(directory):
    year = file.split("_")[-1].split(".")[0]

    if file.endswith(".csv"):
        full_path = directory + file
        df = pd.read_csv(full_path, sep=';', decimal=',')
        df['year'] = year
        if year == 2024:
            df = df.rename(columns={'Ladder score': 'Happiness score'})
        all_data.append(df)

pd.concat(all_data)

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,year,Ladder score
0,3,Iceland,Western Europe,7.5040,7.91458,1.00000,71.0,0.95277,0.56742,0.33066,2017,NaN
1,15,Ireland,Western Europe,6.9770,8.20897,0.96750,71.0,0.87066,0.51053,0.64265,2017,NaN
2,2,Denmark,Western Europe,7.5220,7.92394,0.96309,70.0,0.95102,0.42392,0.86316,2017,NaN
3,47,Uzbekistan,Commonwealth of Independent States,5.9710,4.20385,0.96175,62.0,1.00000,0.49636,0.53096,2017,NaN
4,8,New Zealand,North America and ANZ,7.3140,7.51407,0.96127,71.0,0.93287,0.59661,0.82449,2017,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
147,149,Central African Republic,Sub-Saharan Africa,3.4759,0.26728,0.00000,45.0,0.42237,0.44491,0.94699,2020,NaN
148,150,Rwanda,Sub-Saharan Africa,3.3123,2.23367,0.33787,61.0,0.87136,0.41365,0.08932,2020,NaN
149,151,Zimbabwe,Sub-Saharan Africa,3.2992,2.76938,0.67709,56.0,0.54438,0.26561,0.84821,2020,NaN
150,152,South Sudan,Sub-Saharan Africa,2.8166,1.88122,0.35751,51.0,0.09464,0.36843,0.79151,2020,NaN
151,153,Afghanistan,South Asia,2.5669,1.95686,0.23032,53.0,0.00000,0.23733,0.99770,2020,NaN